sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
gemfile:
  - gemfiles/graphql_1.8.gemfile
  - gemfiles/graphql_1.9.gemfile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: "bundle exec rake"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
